name: hello-world # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The best hello world ever! # 79 char long summary
description: |
  Print hello world to standard out.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hello-world:
    command: bin/hello-world
    plugs:
      - home

parts:
  hello-world:
    plugin: go
    source-type: git
    source: https://github.com/ernestl/hello-world

build-snaps:
  - go 
